BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS questions (id INTEGER PRIMARY KEY, question TEXT, optionA TEXT, optionB TEXT, optionC TEXT, optionD TEXT, answer_index INTEGER);
CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY, email TEXT, password TEXT, username TEXT);
CREATE TABLE IF NOT EXISTS submissions (id INTEGER PRIMARY KEY AUTOINCREMENT, user_email TEXT, timestamp TEXT, total_questions INTEGER, attempted INTEGER, not_answered INTEGER, correct INTEGER, wrong INTEGER, marks INTEGER, answers TEXT);
INSERT INTO questions (id, question, optionA, optionB, optionC, optionD, answer_index) VALUES (1, 'Which company used “Blue Ocean Strategy” by creating an uncontested market space in the entertainment industry?', 'Netflix', 'Cirque du Soleil', 'Spotify', 'Amazon', 0);
INSERT INTO questions (id, question, optionA, optionB, optionC, optionD, answer_index) VALUES (2, 'Why do many startups fail within the first 5 years?', 'Lack of investors', 'Poor product quality', 'No market need', 'High employee turnover', 0);
INSERT INTO questions (id, question, optionA, optionB, optionC, optionD, answer_index) VALUES (3, 'What does MVP stand for in startups?', 'Most Valuable Product', 'Minimum Viable Product', 'Maximum Value Proposition', 'Market Validation Process', 0);
INSERT INTO questions (id, question, optionA, optionB, optionC, optionD, answer_index) VALUES (4, 'Which company was originally called ''BackRub''?', 'Amazon', 'Google', 'Facebook', 'Yahoo', 0);
INSERT INTO questions (id, question, optionA, optionB, optionC, optionD, answer_index) VALUES (5, 'Which Indian startup is a top food delivery app?', 'Flipkart', 'Ola', 'Swiggy', 'Paytm', 0);
INSERT INTO questions (id, question, optionA, optionB, optionC, optionD, answer_index) VALUES (6, 'A Unicorn startup is valued at:', '$10 million', '$100 million', '$500 million', '$1 billion', 0);
INSERT INTO questions (id, question, optionA, optionB, optionC, optionD, answer_index) VALUES (7, 'Angel Investors are:', 'Government officials', 'Early-stage investors', 'Bank loan officers', 'Venture capital firms', 0);
INSERT INTO questions (id, question, optionA, optionB, optionC, optionD, answer_index) VALUES (8, 'Name the 2016 Indian initiative to support startups.', 'Digital India', 'Startup India', 'Make in India', 'Skill India', 0);
INSERT INTO questions (id, question, optionA, optionB, optionC, optionD, answer_index) VALUES (9, 'Intellectual Property (IP) includes:', 'Patents, trademarks, copyrights', 'Office buildings', 'Company vehicles', 'Employee salaries', 0);
INSERT INTO questions (id, question, optionA, optionB, optionC, optionD, answer_index) VALUES (10, '''Burn rate'' refers to:', 'Employee turnover', 'Rate of spending capital', 'Rate of customer growth', 'Share market loss', 0);
INSERT INTO questions (id, question, optionA, optionB, optionC, optionD, answer_index) VALUES (11, 'A ''Pitch Deck'' is:', 'A marketing campaign', 'Startup presentation to investors', 'Office workspace', 'Customer survey form', 0);
INSERT INTO questions (id, question, optionA, optionB, optionC, optionD, answer_index) VALUES (12, 'What does CEO stand for?', 'Chief Economic Officer', 'Chief Executive Officer', 'Corporate Executive Officer', 'Chief Efficiency Officer', 0);
INSERT INTO questions (id, question, optionA, optionB, optionC, optionD, answer_index) VALUES (13, 'Who is the founder of Amazon?', 'Bill Gates', 'Elon Musk', 'Jeff Bezos', 'Mark Zuckerberg', 0);
INSERT INTO questions (id, question, optionA, optionB, optionC, optionD, answer_index) VALUES (14, 'Which company owns Instagram?', 'Twitter', 'Meta (Facebook)', 'Microsoft', 'Snapchat', 0);
INSERT INTO questions (id, question, optionA, optionB, optionC, optionD, answer_index) VALUES (15, 'Which of these companies started in a college dorm room?', 'Facebook', 'Tata', 'Reliance', 'Infosys', 0);
INSERT INTO questions (id, question, optionA, optionB, optionC, optionD, answer_index) VALUES (16, 'The founder of Facebook is:', 'Sundar Pichai', 'Mark Zuckerberg', 'Larry Page', 'Jack Dorsey', 0);
INSERT INTO questions (id, question, optionA, optionB, optionC, optionD, answer_index) VALUES (17, 'Which Indian startup is famous for digital payments and wallet services?', 'Paytm', 'Rupay', 'PhonePe', 'GPay', 0);
INSERT INTO questions (id, question, optionA, optionB, optionC, optionD, answer_index) VALUES (18, 'Who is the CEO of Tesla?', 'Sundar Pichai', 'Satya Nadella', 'Elon Musk', 'Steve Jobs', 0);
INSERT INTO questions (id, question, optionA, optionB, optionC, optionD, answer_index) VALUES (19, 'Which startup is known for online food delivery with a red logo?', 'Ola', 'Swiggy', 'Zomato', 'Dunzo', 0);
INSERT INTO questions (id, question, optionA, optionB, optionC, optionD, answer_index) VALUES (20, 'What is the term for a startup valued at over $1 billion?', 'Dragon', 'Unicorn', 'Phoenix', 'Titan', 0);
INSERT INTO questions (id, question, optionA, optionB, optionC, optionD, answer_index) VALUES (21, 'Which Hyderabad startup became India’s first private company to launch a rocket into space?', 'Agnikul Cosmos', 'Team Indus', 'Skyroot Aerospace', 'Bellatrix Aerospace', 0);
INSERT INTO questions (id, question, optionA, optionB, optionC, optionD, answer_index) VALUES (22, 'Which Kochi startup is often called the ''SurveyMonkey of India''?', 'CareStack', 'Entri', 'SurveySparrow', 'Toffee Ride', 0);
INSERT INTO questions (id, question, optionA, optionB, optionC, optionD, answer_index) VALUES (23, 'What is the sector focus of Hyderabad startup ''Recykal''?', 'E-commerce', 'Waste management & recycling', 'FinTech', 'Healthcare', 0);
INSERT INTO questions (id, question, optionA, optionB, optionC, optionD, answer_index) VALUES (24, 'UrbanKisaan, a Hyderabad startup, is well-known for:', 'Food delivery', 'Vertical farming & hydroponics', 'Online grocery retail', 'Agriculture equipment sales', 0);
INSERT INTO questions (id, question, optionA, optionB, optionC, optionD, answer_index) VALUES (25, 'Which South Indian startup is a leader in AI-powered HR and payroll software?', 'Freshworks', 'Keka HR', 'Zoho', 'Darwinbox', 0);
INSERT INTO questions (id, question, optionA, optionB, optionC, optionD, answer_index) VALUES (26, 'The startup Genrobotics, from Kerala, is solving which social problem?', 'Online learning', 'Manual scavenging', 'Urban traffic congestion', 'Water pollution', 0);
INSERT INTO questions (id, question, optionA, optionB, optionC, optionD, answer_index) VALUES (27, 'Which South Indian unicorn was founded in Chennai and is known for SaaS solutions?', 'Flipkart', 'Freshworks', 'Swiggy', 'Ola', 0);
INSERT INTO questions (id, question, optionA, optionB, optionC, optionD, answer_index) VALUES (28, 'Which startup founded in Bangalore offers personalized health & diet solutions through an app?', 'CureFit', 'HealthifyMe', 'Practo', 'mfine', 0);
INSERT INTO questions (id, question, optionA, optionB, optionC, optionD, answer_index) VALUES (29, 'Which Kerala startup created the children’s learning app ''Toffee Ride''?', 'CareStack', 'Toffee Ride', 'Entri', 'Foradian', 0);
INSERT INTO questions (id, question, optionA, optionB, optionC, optionD, answer_index) VALUES (30, '''Ather Energy'', headquartered in Bangalore, is famous for making:', 'Electric scooters', 'Solar panels', 'Agricultural drones', 'Food processing machines', 0);
INSERT INTO questions (id, question, optionA, optionB, optionC, optionD, answer_index) VALUES (31, 'Which Hyderabad-based space startup is developing small-lift orbital launch vehicles?', 'Agnikul Cosmos', 'Bellatrix Aerospace', 'Skyroot Aerospace', 'Team Indus', 0);
INSERT INTO questions (id, question, optionA, optionB, optionC, optionD, answer_index) VALUES (32, 'The Kochi-based startup CareStack is designed for which sector?', 'FinTech', 'Dental practice management', 'Real estate', 'Waste management', 0);
INSERT INTO questions (id, question, optionA, optionB, optionC, optionD, answer_index) VALUES (33, 'Which South Indian startup is known for smoothies and health cafés across India?', 'Raw Pressery', 'Drunken Monkey', 'Chai Point', 'Epigamia', 0);
INSERT INTO questions (id, question, optionA, optionB, optionC, optionD, answer_index) VALUES (34, 'Falguni Nayar is associated with Nykaa. Which South Indian woman entrepreneur founded Biocon?', 'Vandana Luthra', 'Kiran Mazumdar-Shaw', 'Suchi Mukherjee', 'Meena Ganesh', 0);
INSERT INTO questions (id, question, optionA, optionB, optionC, optionD, answer_index) VALUES (35, 'Which Bengaluru-based startup created the popular workplace communication tool ''Flock''?', 'Zoho', 'Directi', 'Bhavin Turakhia’s startup', 'Freshworks', 0);
INSERT INTO questions (id, question, optionA, optionB, optionC, optionD, answer_index) VALUES (36, 'Which startup from Kochi builds a robot called ''Bandicoot'' to address manual scavenging?', 'Genrobotics', 'CareStack', 'Entri', 'Toffee Ride', 0);
INSERT INTO questions (id, question, optionA, optionB, optionC, optionD, answer_index) VALUES (37, 'Which Kochi based ed-tech startup provides courses & study materials for regional exams in local languages?', 'CareStack', 'Toffee Ride', 'Entri', 'Foradian', 0);
INSERT INTO questions (id, question, optionA, optionB, optionC, optionD, answer_index) VALUES (38, 'What does the startup ''Netrasemi'', based in Thiruvananthapuram, specialize in?', 'AR/VR education', 'Semiconductor chips (IoT / Edge-AI)', 'Organic farming tech', 'Logistics services', 0);
INSERT INTO questions (id, question, optionA, optionB, optionC, optionD, answer_index) VALUES (39, 'Which startup headquartered in Hyderabad offers cloud-based human resource and payroll management software?', 'Freshworks', 'Keka HR', 'Darwinbox', 'Zoho', 0);
INSERT INTO questions (id, question, optionA, optionB, optionC, optionD, answer_index) VALUES (40, 'What is ''Recykal'' (based in Hyderabad) doing?', 'Marketplace for handmade crafts', 'Waste management / digitizing recycling operations', 'Fintech for small businesses', 'Food delivery startup', 0);
INSERT INTO questions (id, question, optionA, optionB, optionC, optionD, answer_index) VALUES (41, 'The startup Skyroot Aerospace, from Hyderabad, is known for working in what field?', 'Food tech', 'Rocket / space launch vehicles', 'Health monitoring wearables', 'Ride-hailing services', 0);
INSERT INTO questions (id, question, optionA, optionB, optionC, optionD, answer_index) VALUES (42, 'Which Kerala startup focuses on dental practice management software in cloud?', 'CareStack', 'Toffee Ride', 'Entri', 'Foradian', 0);
INSERT INTO questions (id, question, optionA, optionB, optionC, optionD, answer_index) VALUES (43, 'What does ''SurveySparrow'' (from Kochi) provide?', 'Financial services', 'Survey/feedback platform', 'Agricultural tools', 'Fitness coaching', 0);
INSERT INTO questions (id, question, optionA, optionB, optionC, optionD, answer_index) VALUES (44, 'Which startup from Kerala has an app that helps children in Classes I to IV through interactive content?', 'CareStack', 'Toffee Ride', 'Entri', 'Foradian', 0);
INSERT INTO questions (id, question, optionA, optionB, optionC, optionD, answer_index) VALUES (45, '''UrbanKisaan'' is a Hyderabad startup. What sector is it in?', 'FinTech', 'Agritech (urban farming / vertical/hydroponic farms)', 'E-commerce', 'EdTech', 0);
INSERT INTO questions (id, question, optionA, optionB, optionC, optionD, answer_index) VALUES (46, 'Which startup from Kerala developed a vernacular learning platform for affordable skill training?', 'CareStack', 'Toffee Ride', 'Entri.app', 'Foradian', 0);
INSERT INTO questions (id, question, optionA, optionB, optionC, optionD, answer_index) VALUES (47, 'What is the main product of ''ClusterDev Technologies'' from Kerala?', 'Language typing and sticker apps across Indian native languages', 'Drone manufacturing', 'Organic food delivery', 'Healthcare diagnostics', 0);
INSERT INTO questions (id, question, optionA, optionB, optionC, optionD, answer_index) VALUES (48, 'Which startup from Telangana works in battery energy storage systems and electric mobility?', 'PURE Energy (Pure EV)', 'CareStack', 'Entri', 'Toffee Ride', 0);
INSERT INTO questions (id, question, optionA, optionB, optionC, optionD, answer_index) VALUES (49, 'Which of the following is a South Indian startup focusing on fitness/wellness/nutrition via AI + human experts?', 'Entri', 'HealthifyMe', 'Keka HR', 'Skyroot Aerospace', 0);
INSERT INTO questions (id, question, optionA, optionB, optionC, optionD, answer_index) VALUES (50, 'In 2021, a Kochi-based startup developed an AI-powered smart helmet to detect drowsiness. Which startup?', 'Netradyne', 'Glider AI', 'Raksha SafeDrive', 'ASIMOV Robotics', 0);
INSERT INTO users (id, email, password, username) VALUES (1, 'jayamanisuganantham@gmail.com', '6369310961', NULL);
INSERT INTO users (id, email, password, username) VALUES (2, 'santheesh1812@gmail.com', '7358982558', NULL);
INSERT INTO users (id, email, password, username) VALUES (3, 'manishkabecse@gmail.com', '9080665163', NULL);
INSERT INTO users (id, email, password, username) VALUES (4, 'harinimp30@gmail.com', '8148314332', NULL);
INSERT INTO users (id, email, password, username) VALUES (5, 'srinivasanm871@gmail.com', '9514995319', NULL);
INSERT INTO users (id, email, password, username) VALUES (6, 'cpbhava2006@gmail.com', '8248890779', NULL);
INSERT INTO users (id, email, password, username) VALUES (7, 'harsha41205@gmail.com', '8056840412', NULL);
INSERT INTO users (id, email, password, username) VALUES (8, 'stamil252011@gmail.com', '7538874785', NULL);
INSERT INTO users (id, email, password, username) VALUES (9, 'smsurekashree@gmail.com', '9342787117', NULL);
INSERT INTO users (id, email, password, username) VALUES (10, 'kpvija1907@gmail.com', '8248178401', NULL);
INSERT INTO users (id, email, password, username) VALUES (11, 'vvasundara206@gmail.com', '90365 5400', NULL);
INSERT INTO users (id, email, password, username) VALUES (12, 'tharnikamurugesan8925@gmail.com', '8925575345', NULL);
INSERT INTO users (id, email, password, username) VALUES (13, 'dharman2713@gmail.com', '8825999731', NULL);
INSERT INTO users (id, email, password, username) VALUES (14, 'yogasrieswaran2007@gmail.com', '6381041583', NULL);
INSERT INTO users (id, email, password, username) VALUES (15, 'gokulakrishofficial@gmail.com', '6379537160', NULL);
INSERT INTO users (id, email, password, username) VALUES (16, 'ggunapriya1@gmail.com', '8189948337', NULL);
INSERT INTO users (id, email, password, username) VALUES (17, 'kuromi61hrt@gmail.com', '8144088604', NULL);
INSERT INTO users (id, email, password, username) VALUES (18, 'harivishnu112233@gmail.com', '9360331040', NULL);
INSERT INTO users (id, email, password, username) VALUES (19, 'tharunmunirathinam@gmail.com', '9344205845', NULL);
INSERT INTO users (id, email, password, username) VALUES (20, 'hariprasanth042008@gmail.com', '7200905773', NULL);
INSERT INTO users (id, email, password, username) VALUES (21, 'bavaanish37@gmail.com', '7667862427', NULL);
INSERT INTO users (id, email, password, username) VALUES (22, 'pragadeshmahalingam14@gmail.com', '6369961548', NULL);
INSERT INTO users (id, email, password, username) VALUES (23, 'siraj161996@gmail.com', '7358373253', NULL);
INSERT INTO users (id, email, password, username) VALUES (24, 'balabarathiarumugam@gmail.com', '7010758993', NULL);
INSERT INTO users (id, email, password, username) VALUES (25, 'jananim945@gmail.com', '9600942330', NULL);
INSERT INTO users (id, email, password, username) VALUES (26, 'madhivathanan3@gmail.com', '9361381908', NULL);
INSERT INTO users (id, email, password, username) VALUES (27, 'manashwiniraj17@gmail.com', '8122084320', NULL);
INSERT INTO users (id, email, password, username) VALUES (28, 'afreenshowkathali2237@gmail.com', '9384083737', NULL);
INSERT INTO users (id, email, password, username) VALUES (29, 'vsdharshini2007@gmail.com', '8778797200', NULL);
INSERT INTO users (id, email, password, username) VALUES (30, 'roshinipriyakamarajan@gmail.com', '8870681805', NULL);
INSERT INTO users (id, email, password, username) VALUES (31, 'keerthikas1957@gmail.com', '9361446397', NULL);
INSERT INTO users (id, email, password, username) VALUES (32, 'swathikasenthilkumar63@gmail.com', '9629547587', NULL);
INSERT INTO users (id, email, password, username) VALUES (33, 'bb8217654531@gmail.com', '9363495501', NULL);
INSERT INTO users (id, email, password, username) VALUES (34, 'dhanumallaiyan07@gmail.com', '8122293251', NULL);
INSERT INTO users (id, email, password, username) VALUES (35, 'atchayar36@gmail.com', '8838101199', NULL);
INSERT INTO users (id, email, password, username) VALUES (36, 'kavipriya3118@gmail.com', '8973168428', NULL);
INSERT INTO users (id, email, password, username) VALUES (37, 'vijiramadoss41@gmail.com', '7448529209', NULL);
INSERT INTO users (id, email, password, username) VALUES (38, 'kumarvanitha2007@gmail.com', '8838657683', NULL);
INSERT INTO users (id, email, password, username) VALUES (39, 'dhivyasra69@gmail.com', '9047794608', NULL);
INSERT INTO users (id, email, password, username) VALUES (40, 'deepikasanthakumar1@gmail.com', '7200427554', NULL);
INSERT INTO users (id, email, password, username) VALUES (41, 'jaikumarpalani5@gmail.com', '8754075020', NULL);
INSERT INTO users (id, email, password, username) VALUES (42, 'varuna22042002@gmail.com', '9500939090', NULL);
INSERT INTO users (id, email, password, username) VALUES (43, 'sureka1114@gmail.com', '8438048475', NULL);
INSERT INTO users (id, email, password, username) VALUES (44, 'karunyakarunya9425@gmail.com', '6381760803', NULL);
INSERT INTO users (id, email, password, username) VALUES (45, 'madhumithap0112@gmail.com', '9345904526', NULL);
INSERT INTO users (id, email, password, username) VALUES (46, 'sanjaayslm@gmail.com', '9789750456', NULL);
INSERT INTO users (id, email, password, username) VALUES (47, 'vigneshavatti@gmail.com', '9043798673', NULL);
INSERT INTO users (id, email, password, username) VALUES (48, 'shankaranarayanan21082008@gmail.com', '7708738739', NULL);
INSERT INTO users (id, email, password, username) VALUES (49, 's.vishnupriya6871@gmail.com', '8015026871', NULL);
INSERT INTO users (id, email, password, username) VALUES (50, 'deepielango2007@gmail.com', '9487960073', NULL);
INSERT INTO users (id, email, password, username) VALUES (51, 'rkmhairunisha78@gmail.com', '9715324780', NULL);
INSERT INTO users (id, email, password, username) VALUES (52, 'dhivya2009123456@gmail.com', '8072890645', NULL);
INSERT INTO users (id, email, password, username) VALUES (53, 'sdharshini1703@gmail.com', '8438391703', NULL);
INSERT INTO users (id, email, password, username) VALUES (54, 'vijisaravanan8595@gmail.com', '9080155520', NULL);
INSERT INTO users (id, email, password, username) VALUES (55, 'akshayashanmugam17@gmail.com', '9042417108', NULL);
INSERT INTO users (id, email, password, username) VALUES (56, 'dikshasriraju@gmail.com', '7339018109', NULL);
INSERT INTO users (id, email, password, username) VALUES (57, 'darshitaanu@gmail.com', '9384923594', NULL);
INSERT INTO users (id, email, password, username) VALUES (58, 'akshadabhaskarsuryawanshi@gmail.com', '9342965726', NULL);
INSERT INTO users (id, email, password, username) VALUES (59, 'aishwarya21102007@gmail.com', '9342201965', NULL);
INSERT INTO users (id, email, password, username) VALUES (60, 'dikshithavishu30@gmail.com', '8825768168', NULL);
INSERT INTO users (id, email, password, username) VALUES (61, 'suganthim1038@gmail.com', '6369659748', NULL);
INSERT INTO users (id, email, password, username) VALUES (62, 'saranyavenkatesh1694@gmail.com', '7305179376', NULL);
INSERT INTO users (id, email, password, username) VALUES (63, 'nishhhkutty@gmail.com', '8220674606', NULL);
INSERT INTO users (id, email, password, username) VALUES (64, 'kiruthikakeerthu07@gmail.com', '9080514270', NULL);
INSERT INTO users (id, email, password, username) VALUES (65, 'kavyadharshani2008@gmail.com', '9080018488', NULL);
INSERT INTO users (id, email, password, username) VALUES (66, 'akshayalaxmi57@gmail.com', '8122920129', NULL);
INSERT INTO users (id, email, password, username) VALUES (67, 'pjananipachiyannan@gmail.com', '9344218898', NULL);
INSERT INTO users (id, email, password, username) VALUES (68, 'jamunagovindhan9095@gmail.com', '8148425515', NULL);
INSERT INTO users (id, email, password, username) VALUES (69, 'vignesh.kuppan1538@gmail.com', '6385363817', NULL);
INSERT INTO users (id, email, password, username) VALUES (70, 'gunasriddgms@gmail.com', '6369592043', NULL);
INSERT INTO users (id, email, password, username) VALUES (71, 'divyadharshini131123@gmail.com', '9362657084', NULL);
INSERT INTO users (id, email, password, username) VALUES (72, 'diwakarpraveen165@gmail.com', '7010144856', NULL);
INSERT INTO users (id, email, password, username) VALUES (73, 'sudhikshamuralikrishnan2008@gmail.com', '9976531365', NULL);
INSERT INTO users (id, email, password, username) VALUES (74, 'cdhanush850@gmail.com', '8015939363', NULL);
INSERT INTO users (id, email, password, username) VALUES (75, 'madhumithabala2007@gmail.com', '8925352590', NULL);
INSERT INTO users (id, email, password, username) VALUES (76, 'dhanusri8248@gmail.com', '8248278503', NULL);
INSERT INTO users (id, email, password, username) VALUES (77, 'thirisham223@gmail.com', '8778435310', NULL);
INSERT INTO users (id, email, password, username) VALUES (78, 'ramyaramzzz55@gmail.com', '8098696024', NULL);
INSERT INTO users (id, email, password, username) VALUES (79, 'karthikasudar1@gmail.com', '84388 23587', NULL);
INSERT INTO users (id, email, password, username) VALUES (80, 'perumalrajsem@gmail.com', '9360724984', NULL);
INSERT INTO users (id, email, password, username) VALUES (81, 'vetrikishore94@gmail.com', '9487012806', NULL);
INSERT INTO users (id, email, password, username) VALUES (82, 'sangeetha10121992@gmail.com', '7604803820', NULL);
INSERT INTO users (id, email, password, username) VALUES (83, 'kowsicka2007@gmail.com', '9500408256', NULL);
INSERT INTO users (id, email, password, username) VALUES (84, 'k8693466@gmail.com', '9655799740', NULL);
INSERT INTO users (id, email, password, username) VALUES (85, 'mahaabirami3003@gmail.com', '9159183037', NULL);
INSERT INTO users (id, email, password, username) VALUES (86, 'gkrishnaraj07@gmail.com', '8838086234', NULL);
INSERT INTO users (id, email, password, username) VALUES (87, 'manickamchandralekha@gmail.com', '7010771855', NULL);
INSERT INTO users (id, email, password, username) VALUES (88, 'vvaishnavaprasath@gmail.com', '9345621105', NULL);
INSERT INTO users (id, email, password, username) VALUES (89, 'ledcapital6@gmail.com', '81221 51584', NULL);
INSERT INTO users (id, email, password, username) VALUES (90, 'ranjith240607@gmail.com', '7639070424', NULL);
INSERT INTO users (id, email, password, username) VALUES (91, 'mahalingammaha74@gmail.com', '7092479098', NULL);
INSERT INTO users (id, email, password, username) VALUES (92, 'sumithrasrinivasan1093@gmail.com', '6382558198', NULL);
INSERT INTO users (id, email, password, username) VALUES (93, 'vaishu23rv@gmail.com', '8778828008', NULL);
INSERT INTO users (id, email, password, username) VALUES (94, 'swathiramasamy2008@gmail.com', '7603944071', NULL);
INSERT INTO users (id, email, password, username) VALUES (95, 'sinthujaboopathi26@gmail.com', '8610170189', NULL);
INSERT INTO users (id, email, password, username) VALUES (96, 'sathyabala8015@gmail.com', '8056309652', NULL);
INSERT INTO users (id, email, password, username) VALUES (97, 'sobanarathish9955@gmail.com', '8838810893', NULL);
INSERT INTO users (id, email, password, username) VALUES (98, 'harinimldh@gmail.com', '6383561507', NULL);
INSERT INTO users (id, email, password, username) VALUES (99, 'jeevitha13818@gmail.com', '8438033802', NULL);
INSERT INTO users (id, email, password, username) VALUES (100, 'megalasundhar811@gmail.com', '9080139550', NULL);
INSERT INTO users (id, email, password, username) VALUES (101, 'yuvaraniravi12@gmail.com', '9655299452', NULL);
INSERT INTO users (id, email, password, username) VALUES (102, 'sangeethassms2008@gmail.com', '7305906294', NULL);
INSERT INTO users (id, email, password, username) VALUES (103, 'ngopika67@gmail.com', '9080139550', NULL);
INSERT INTO users (id, email, password, username) VALUES (104, 'saranyapraveen307@gmail.com', '8438224307', NULL);
INSERT INTO users (id, email, password, username) VALUES (105, 'boomikaprema2008@gmail.com', '9786834429', NULL);
INSERT INTO users (id, email, password, username) VALUES (106, 'kanmanichandra2008n@gmail.com', '6369181919', NULL);
INSERT INTO users (id, email, password, username) VALUES (107, 'kishorekishore2650@gmail.com', '9344074554', NULL);
INSERT INTO users (id, email, password, username) VALUES (108, 'nagulan23042008@gmail.com', '9500869173', NULL);
INSERT INTO users (id, email, password, username) VALUES (109, 'kavins2876@gmail.com', '8438224307', NULL);
INSERT INTO users (id, email, password, username) VALUES (110, 'madhankavi2007@gmail.com', '8015581439', NULL);
INSERT INTO users (id, email, password, username) VALUES (111, 'revathilakshminarayanan2007@gmail.com', '8807564253', NULL);
INSERT INTO users (id, email, password, username) VALUES (112, 'kalaakash81@gmail.com', '8248156934', NULL);
INSERT INTO users (id, email, password, username) VALUES (113, 'sakthig253@gmail.com', '9688867722', NULL);
INSERT INTO users (id, email, password, username) VALUES (114, 'anusrivijayakumar2008@gmail.com', '8056508930', NULL);
INSERT INTO users (id, email, password, username) VALUES (115, 'akshayavadivel234@gmail.com', '8248737837', NULL);
COMMIT;